"use client";

import { useEffect, useRef, useState } from "react";

// 30×20 pixel-art cat: hand-drawn silhouette (F fur, L light), with the
// 1px ink outline generated by an edge pass, then eye/ears/collar overlaid.
// preview the art in a terminal with: node scripts/preview-cat.mjs
const W = 30;
const H = 20;
const PX = 3; // on-screen size of one pixel

const SHAPE = [
  ".....................F....F...",
  "....................FFF..FFF..",
  "....................FFFFFFFF..",
  "..FF...............FFFFFFFFF..",
  ".FFF...............FFFFFFFFFF.",
  ".FFF...............FFFFFFFFFF.",
  ".FFF...............FFFFFFFFFF.",
  ".FFF......FFFFFFFFFFFFFFFFFFF.",
  "..FFF....FFFFFFFFFFFFFFFFFFFF.",
  "...FFF..FFFFFFFFFFFFFFFFFFFF..",
  "....FFFFFFFFFFFFFFFFFFFFFFF...",
  "....FFFFFFFFFFFFFFFFFFFFFF....",
  "....FFFFFFFFLLLLLLFFFFFF......",
  "....FFFFFFFLLLLLLLLFFFFF......",
  "....FFFFFFFLLLLLLLLFFFFF......",
  "..............................",
  "..............................",
  "..............................",
  "..............................",
  "..............................",
];

// [xStart, width] per leg, drawn rows 15..19
const LEGS_A: [number, number][] = [
  [5, 3],
  [10, 3],
  [17, 3],
  [22, 3],
];
const LEGS_B: [number, number][] = [
  [6, 3],
  [9, 3],
  [18, 3],
  [21, 3],
];

function compose(legs: [number, number][], blink: boolean): string[] {
  const g = SHAPE.map((r) => r.split(""));
  for (const [x0, w] of legs) {
    for (let y = 15; y < H; y++) {
      for (let x = x0; x < x0 + w; x++) g[y][x] = "F";
    }
  }
  const isFill = (x: number, y: number) =>
    x >= 0 && x < W && y >= 0 && y < H && g[y][x] !== ".";
  const edges: [number, number][] = [];
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      if (g[y][x] === ".") continue;
      if (!isFill(x - 1, y) || !isFill(x + 1, y) || !isFill(x, y - 1) || !isFill(x, y + 1)) {
        edges.push([x, y]);
      }
    }
  }
  for (const [x, y] of edges) g[y][x] = "K";

  const set = (x: number, y: number, v: string) => {
    if (g[y][x] !== ".") g[y][x] = v;
  };
  // inner ears
  set(21, 1, "L");
  set(26, 1, "L");
  // eye (2×2; blink keeps only the bottom row)
  if (!blink) {
    set(25, 5, "E");
    set(26, 5, "E");
  }
  set(25, 6, "E");
  set(26, 6, "E");
  // muzzle
  for (let x = 24; x <= 27; x++) {
    set(x, 8, "L");
    set(x, 9, "L");
  }
  // collar
  for (let x = 19; x <= 23; x++) set(x, 10, "C");
  return g.map((r) => r.join(""));
}

const FRAMES = {
  a: compose(LEGS_A, false),
  b: compose(LEGS_B, false),
  aBlink: compose(LEGS_A, true),
  bBlink: compose(LEGS_B, true),
};

const PIXEL_FILL: Record<string, string> = {
  K: "var(--ink)",
  F: "var(--soft)",
  L: "var(--faint)",
  C: "var(--accent)",
  E: "var(--ink)",
};

function Sprite({ frame, flip }: { frame: string[]; flip: boolean }) {
  return (
    <svg
      viewBox={`0 0 ${W} ${H}`}
      width={W * PX}
      height={H * PX}
      style={{
        display: "block",
        shapeRendering: "crispEdges",
        transform: flip ? "scaleX(-1)" : undefined,
      }}
      aria-hidden="true"
    >
      {frame.flatMap((row, y) =>
        row.split("").map((ch, x) =>
          ch === "." ? null : (
            <rect key={`${x}-${y}`} x={x} y={y} width="1" height="1" fill={PIXEL_FILL[ch]} />
          )
        )
      )}
    </svg>
  );
}

const WALK_MS = 3200;
const STEP_MS = 240;
const BLINK_EVERY_MS = 2900;
const BLINK_MS = 160;

export function LostCat() {
  const [reduced, setReduced] = useState<boolean | null>(null);
  const [x, setX] = useState(8);
  const [dir, setDir] = useState(1);
  const [stepFrame, setStepFrame] = useState(false);
  const [blink, setBlink] = useState(false);
  const xRef = useRef(8);

  useEffect(() => {
    setReduced(window.matchMedia("(prefers-reduced-motion: reduce)").matches);
  }, []);

  // wander: pick a spot, stroll there, pause, repeat
  useEffect(() => {
    if (reduced !== false) return;
    let t: ReturnType<typeof setTimeout>;
    const hop = () => {
      const next = 4 + Math.random() * 78;
      setDir(next > xRef.current ? 1 : -1);
      xRef.current = next;
      setX(next);
      t = setTimeout(hop, WALK_MS + 600 + Math.random() * 2400);
    };
    t = setTimeout(hop, 900);
    return () => clearTimeout(t);
  }, [reduced]);

  // little legs
  useEffect(() => {
    if (reduced !== false) return;
    const tick = setInterval(() => setStepFrame((s) => !s), STEP_MS);
    return () => clearInterval(tick);
  }, [reduced]);

  // blink
  useEffect(() => {
    if (reduced !== false) return;
    const tick = setInterval(() => {
      setBlink(true);
      setTimeout(() => setBlink(false), BLINK_MS);
    }, BLINK_EVERY_MS);
    return () => clearInterval(tick);
  }, [reduced]);

  const frame = blink
    ? stepFrame
      ? FRAMES.bBlink
      : FRAMES.aBlink
    : stepFrame
      ? FRAMES.b
      : FRAMES.a;

  return (
    <div
      className="relative mt-12 h-[100px]"
      style={{ borderBottom: "1px solid var(--line)" }}
      aria-hidden="true"
    >
      <div
        className="absolute bottom-0"
        style={{
          left: `${x}%`,
          transition: reduced ? undefined : `left ${WALK_MS}ms linear`,
        }}
      >
        <Sprite frame={frame} flip={dir < 0} />
      </div>
    </div>
  );
}
